[package]
name = "boreum-lang"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.14.4"
cstree = "0.12.2"
lasso = "0.7.3"
lexical-core = "1.0.5"
miette = "7.4.0"
num-traits = "0.2.19"
num-derive = "0.4.2"
paste = "1.0"

[dependencies.chumsky]
git = "https://github.com/zesterer/chumsky.git"
features = []